# @format
---
- name: Run Laravel migrate and seed
  command: php artisan migrate:fresh --seed --force
  args:
    chdir: "{{ laravel_app_path }}"
  environment:
    APP_ENV: "{{ app_env_map[env] }}"
